[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

; SD library is part of arduino-esp32 core — no extra lib_deps needed
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_RUNNING_CORE=1
