[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = nodemcu
lib_deps =
    adafruit/Adafruit BNO08x@^1.2.3
    mikalhart/TinyGPSPlus@^1.0.3
